import {
  Activity,
  Baby,
  BadgeCheck,
  Briefcase,
  CalendarClock,
  CalendarPlus,
  CheckCircle2,
  ClipboardList,
  FlaskConical,
  FolderClock,
  GraduationCap,
  HeartHandshake,
  History,
  IdCard,
  LayoutDashboard,
  Lock,
  MapPin,
  ShieldCheck,
  Stethoscope,
  Syringe,
  Users,
  type LucideIcon,
} from 'lucide-react';

export const iconMap = {
  Activity,
  Baby,
  BadgeCheck,
  Briefcase,
  CalendarClock,
  CalendarPlus,
  CheckCircle2,
  ClipboardList,
  FlaskConical,
  FolderClock,
  GraduationCap,
  HeartHandshake,
  History,
  IdCard,
  LayoutDashboard,
  Lock,
  MapPin,
  ShieldCheck,
  Stethoscope,
  Syringe,
  Users,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;
